
// UI
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';
export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const SIDEBAR_OPENED = 'SIDEBAR_OPENED';
export const SIDEBAR_CLOSED = 'SIDEBAR_CLOSED';


// FUNCTIONALITY
export const FIND_AERO_TICKETS = 'FIND_AERO_TICKETS';
export const FIND_AERO_TICKETS_SUCCESS = 'FIND_AERO_TICKETS_SUCCESS';
export const FIND_AERO_TICKETS_ERR = 'FIND_AERO_TICKETS_ERR';
